# Generated by Django 6.1 on 2026-08-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculations", "0018_remove_zentra_add_open_meteo_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestModeSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=False,
                        help_text="When enabled, a 100mm storm is injected 2 days into the forecast before every river flow calculation. Click 'Recalculate flood flows' below after changing this for it to take effect.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Test mode",
                "verbose_name_plural": "Test mode",
            },
        ),
    ]
