name: Lint using black code style

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: psf/black@stable
        with:
          options: "--check"
          src: "./manyfews"
          # Keep in sync with .pre-commit-config.yaml and config/manyFEWS.devel.yml
          version: "~= 24.10.0"
